### ISSUE TITLE
Restoring widgets from workflow

### ISSUE THREAD

**Issue by jo-mueller** [haesleinhuepf/napari-workflows#12]
@haesleinhuepf @Cryaaa 

since we were debatting yesterday about this project (and I think already went a few steps in this direction), do you have any preferences about where such a function should reside? I could see it in `napari-workflows`:

- We could write a function `restore widgets` in the newly designed [_io_yaml_v1.py](https://github.com/haesleinhuepf/napari-workflows/blob/main/src/napari_workflows/_io_yaml_v1.py)
- It would require to make `napari-tools-menu` (`make_gui()`, specifically) part of the dependencies to hook the restored widgets to the workflow functionality

Just creating this issue to keep track of the project, feel free to delete it if it has been created elsewhere.

**Comment by haesleinhuepf** [comment]
Very good! I was thinking again of where to put the code for this and I think the right place would be the [assistant repository](https://github.com/clEsperanto/napari_pyclesperanto_assistant/), because the assistant allows to build workflows.

**Comment by haesleinhuepf** [comment]
> It would require to make napari-tools-menu (make_gui(), specifically) part of the dependencies to hook the restored widgets to the workflow functionality

That actually makes sense. Alternatively, we could move the make_gui code here, and use it from [napari-tools-menu](https://github.com/haesleinhuepf/napari-tools-menu/).

**Comment by Cryaaa** [comment]
Since we want to implement the save and load workflow functions into the [workflow inspector plugin](https://github.com/haesleinhuepf/napari-workflow-inspector), should the code maybe reside there? I mean we mostly need the GUI creation when we are working in napari so for me at least it makes sense to keep the code there.

**Comment by jo-mueller** [comment]
> [workflow inspector plugin](https://github.com/haesleinhuepf/napari-workflow-inspector), should the code maybe reside there?

True that. Both napari-workflows and napari-tools-menu are already in the dependencies of the workflow inspector, so this makes sense to me, too.

**Comment by haesleinhuepf** [comment]
The problem with the inspector is that the code there is GPL-licensed and hence lincense-incompatible with other repositories. I would prefer to see the I/O functionality in the assistant.

**Comment by Cryaaa** [comment]
This issue has now been solved in the [napari assistant](https://github.com/haesleinhuepf/napari-assistant) and the code for it was introduced [here](https://github.com/haesleinhuepf/napari-assistant/pull/1).
