### ISSUE TITLE
Data dimension check fails for surfaces and points

### ISSUE THREAD

**Issue by jo-mueller** [haesleinhuepf/napari-workflows#25]
Hi @haesleinhuepf ,

I'm getting errors when using the `nppas.label_to_surface` function on 4D data with the following error message:

```Python
~\Anaconda3\envs\stress\lib\site-packages\napari_workflows\_workflow.py in _slider_updated(self=<napari_workflows._workflow.WorkflowManager object>, event=<Event blocked=False handled=False native=None source=None sources=[] type='current_step'>)
    388         if len(slider) == 4: # a time-slider exists
    389             for l in self.viewer.layers:
--> 390                 if len(l.data.shape) == 4:
        global len = undefined
        l.data.shape = undefined
    391                     self.invalidate(self.workflow.followers_of(l.name))
    392

AttributeError: 'tuple' object has no attribute 'shape'
```

You can reproduce this with the following steps:

- get [this](https://github.com/campaslab/STRESS/blob/main/ExampleTifSequence-InteriorLabel-vsx_2.076um-vsz_3.998um-TimeInterval_3.00min-21timesteps.tif) data
- Binarize in Napari
- Do label to surface
- drag the slider

Thanks for looking into it!

**Comment by haesleinhuepf** [comment]
Hi @jo-mueller ,

thanks for reporting! If you install this the error should be gone:

    pip install napari-workflows==0.2.2

Furthermore, consider installing this to fix follow-up issues: 

    pip install napari-time-slicer==0.4.5 napari-tools-menu==0.1.14

It should then be possible to create surfaces in time-lapse data
