### ISSUE TITLE
Workflow IO

### ISSUE THREAD

**Issue by haesleinhuepf** [haesleinhuepf/napari-workflows#3]
It should be possible to save a workflow as [JSON](https://docs.python.org/3/library/json.html) to disc and reload it. 

The tricky part: 
* When storing a workflow step from the [assistant](https://www.napari-hub.org/plugins/napari-pyclesperanto-assistant), the GUI will show `[input_image, operation_name, other_parameters]` before saving and `[[input_image, other_parameters]]` after reloading. The operation will not be changable anymore. That's ok IMO.
* When loading a workflow from another computer, not all operations may be installed. The user should get a good error message explaining them what to install. Exchanging operations, e.g. `ncupy.threshold_otsu` with `nsbatwm.threshold_otsu` may be technically possible (manually) but automating that is challenging.

**Comment by haesleinhuepf** [comment]
@jo-mueller implemented parts of this in YAML format yesterday. Johannes, can you please give us a link where the code lives?

**Comment by jo-mueller** [comment]
Hi @haesleinhuepf ,
It's in [this](https://github.com/jo-mueller/napari_workflow_hackathon_2022) repository. However, we couldn't get it to work with yaml. Or rather, we could save a workflow in a human-readable form with yaml:

```Python
import yaml 
stream = open(file, 'w')
yaml.dump(workflow_object, stream)
stream.close()
```

Currently, we settled for 
```
import pickle
with open("workflow.pickle", "wb") as fileobj:
    pickle.dump(workflow_object, fileobj)
```

We did find a few leads on how to put this in yaml files [here](https://yaml.readthedocs.io/en/latest/dumpcls.html) and [here](https://stackoverflow.com/questions/65820633/dumping-custom-class-objects-to-a-yaml-file), though.

**Comment by haesleinhuepf** [comment]
This has been done in #9
