### ISSUE TITLE
the first image after loading a file is shown as numpy array, not as an image.

### ISSUE THREAD

**Issue by thawn** [haesleinhuepf/napari-workflows#38]
The first two cells in a generated notebook usually look something like this:

```python
from skimage.io import imread
import pyclesperanto_prototype as cle  # version 0.24.4
```

```python
image0_cx2 = imread("blobs.tif")
image0_cx2
```

since switching from cle.imread to skimage.io.imread, the returned image is a numpy array and therefore the output is not displayed as an image but as a matrix of numbers.

I recommend to change the first two cells to:

```python
from skimage.io import imread
import pyclesperanto_prototype as cle  # version 0.24.4
import stackview
```

```python
image0_cx2 = imread("blobs.tif")
stackview.insight(image0_cx2)
```

notebook to reproduce the error:
[reproduce.ipynb.zip](https://github.com/user-attachments/files/16610770/reproduce.ipynb.zip)

**Comment by haesleinhuepf** [comment]
Yes, this makes total sense. We need to modify the code generator in "_workflow.py". E.g. this:

```
elif notebook:
    code.append(result_name + "\n")
```

Should be replaced by this:
```
elif notebook:
    code.append(f"stackview.insight({result_name})\n")
```

And "import stackview" should be added to the list of imports in this line:
```
 imports = ["from skimage.io import imread"]
```

**Comment by haesleinhuepf** [comment]
Hi @thawn ,

I just release a new version with your modification. Please try it out:

    pip install napari-workflows==0.2.11

And let me know if it works. Thanks!

Bestt,
Robert

**Comment by thawn** [comment]
Hi @haesleinhuepf,

I just tested it and it works 😄 

Thanks a lot for the fast support.

Cheers,

Till

**Comment by haesleinhuepf** [comment]
Thanks for reporting this!
